#!/usr/bin/env node
/**
 * Render a project composition to /output/<composition-id>.mp4
 * Usage: node render.mjs <composition-id>   (or: npm run render -- <composition-id>)
 *
 * Each project is registered as a composition whose id is the project name
 * (see src/Root.tsx, generated by the pipeline). Pass that id to render it.
 */

import { execSync } from "child_process";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const compId = process.argv[2];
if (!compId) {
  console.error("Usage: node render.mjs <composition-id>");
  console.error("List composition ids with:  npx remotion compositions");
  process.exit(1);
}

const outputPath = resolve(__dirname, "../../output", `${compId}.mp4`);

console.log(`🎬 Rendering ${compId} → ${outputPath}`);

execSync(`npx remotion render "${compId}" "${outputPath}"`, {
  stdio: "inherit",
  cwd: __dirname,
});
